name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'wiki/**'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Build Sphinx documentation
      run: |
        cd docs
        
        # Create _static directory if it doesn't exist
        mkdir -p _static
        
        # Create basic conf.py if it doesn't exist
        if [ ! -f conf.py ]; then
          cat > conf.py << 'EOF'
import os
import sys
sys.path.insert(0, os.path.abspath('..'))

project = 'Gopnik'
copyright = '2024, Gopnik Development Team'
author = 'Gopnik Development Team'
release = '0.1.0'

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
EOF
        fi
        
        # Create basic index.rst if it doesn't exist
        if [ ! -f index.rst ]; then
          cat > index.rst << 'EOF'
Welcome to Gopnik's documentation!
==================================

Gopnik is an AI-powered forensic-grade deidentification toolkit.

Contents:
=========

.. toctree::
   :maxdepth: 2

   Installation <../README.md>
   User Guide <user-guide/index>
   Developer Guide <developer-guide/index>

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
EOF
        fi
        
        # Build documentation with verbose output
        sphinx-build -b html . _build/html || {
          echo "Sphinx build failed, creating basic documentation"
          mkdir -p _build/html
          echo '<html><body><h1>Gopnik Documentation</h1><p>Documentation is being built. Please check back later.</p></body></html>' > _build/html/index.html
        }
        
        # Copy built docs to _site for GitHub Pages
        mkdir -p _site
        cp -r _build/html/* _site/
        
        # Create index.html redirect if needed
        if [ ! -f _site/index.html ]; then
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=./index.html"></head><body></body></html>' > _site/index.html
        fi

    - name: Copy additional documentation
      run: |
        # Copy wiki content
        mkdir -p docs/_site/wiki
        cp wiki/*.md docs/_site/wiki/ || true
        
        # Copy README as additional content
        cp README.md docs/_site/readme.md || true

    - name: Update GitHub Wiki
      run: |
        echo "🔄 Updating GitHub Wiki..."
        
        # Clone wiki repository
        git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki-repo || {
          echo "⚠️ Wiki not enabled or accessible, skipping wiki update"
          exit 0
        }
        
        cd wiki-repo
        
        # Function to check if file should be ignored
        should_ignore_file() {
          local filename="$1"
          local gitignore_file="../wiki/.gitignore"
          
          # If no .gitignore exists, don't ignore anything
          if [ ! -f "$gitignore_file" ]; then
            return 1
          fi
          
          # Check each pattern in .gitignore
          while IFS= read -r pattern || [ -n "$pattern" ]; do
            # Skip empty lines and comments
            if [[ -z "$pattern" || "$pattern" =~ ^[[:space:]]*# ]]; then
              continue
            fi
            
            # Remove leading/trailing whitespace
            pattern=$(echo "$pattern" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            
            # Skip empty patterns
            if [[ -z "$pattern" ]]; then
              continue
            fi
            
            # Use case statement for better pattern matching
            case "$filename" in
              $pattern)
                return 0
                ;;
            esac
          done < "$gitignore_file"
          
          return 1
        }
        
        # Copy updated wiki content (respecting .gitignore)
        for file in ../wiki/*.md; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            
            # Direct check for files that should be excluded
            case "$filename" in
              "Wiki-Setup-Troubleshooting.md"|*troubleshooting*|*Troubleshooting*|*-dev.md|*-internal.md|*-draft.md|*-wip.md|*-private.md|*-secret.md|*-config.md|*-credentials.md|TODO.md|NOTES.md|SCRATCH.md)
                echo "⏭️ Skipping $filename (excluded from public wiki)"
                continue
                ;;
            esac
            
            # Also check .gitignore file if it exists
            if should_ignore_file "$filename"; then
              echo "⏭️ Skipping $filename (ignored by .gitignore)"
              continue
            fi
            
            cp "$file" "$filename"
            git add "$filename"
            echo "✅ Updated $filename in wiki"
          fi
        done
        
        # Check if there are changes to commit
        if ! git diff --staged --quiet; then
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "📚 Auto-update wiki from documentation build
          
          Updated from main repository commit: ${{ github.sha }}
          Triggered by documentation deployment"
          
          git push origin master
          echo "🚀 Wiki updated successfully!"
        else
          echo "ℹ️ No wiki changes to commit"
        fi
        
        cd ..
        rm -rf wiki-repo

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4